spring.application.name=SpringBootUsingJwt
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_authentication
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=exI0GYWCxp5bykRhhlOmnRNffKueyXREgReuKy7h9EO
security.jwt.issuer=SpringBootUsingJwt
